### ISSUE TITLE
Profile hive map containers

### ISSUE THREAD

**Issue by vgrivel** [criteo/babar#15]
Hi, 
I'm trying to profile a hive query with many sub-queries and joins. The report does not show any container that belong to the mapper but only the one for the reducer. 
Is it intended to not be able to view the mapper containers ?

Steps taken:
Add at the beginning of the hql file:

```
ADD FILE /tmp/babar-agent-0.2.0-SNAPSHOT.jar;
SET mapreduce.map.java.opts="-javaagent:./babar-agent-0.2.0-SNAPSHOT.jar=StackTraceProfiler,JVMProfiler[reservedMB=2560],ProcFSProfiler";
SET mapreduce.reduce.java.opts="-javaagent:./babar-agent-0.2.0-SNAPSHOT.jar=StackTraceProfiler,JVMProfiler[reservedMB=3584],ProcFSProfiler";
```
yarn logs --applicationId application_1111111111111_1111 > myapps.log
java -jar /tmp/babar-processor-0.2.0-SNAPSHOT.jar myapps.log 

Environment: 
HDP-2.3.4
Hive 1.2.1
Hadoop 2.7.1

Thanks

**Comment by vgrivel** [comment]
I found my problem, I was redefining mapreduce.map.java.opts lower on the script.

**Comment by BenoitHanotte** [comment]
Hello @vgrivel glad to hear it worked, I was about to run a query to check but you've been faster :)
