### ISSUE TITLE
scala-maven-plugin not found

### ISSUE THREAD

**Issue by andres-lago** [criteo/babar#16]
I had the following error after my first "mvn clean install": 

`[WARNING] Some problems were encountered while building the effective model for                                                                  com.criteo.babar:babar-processor:jar:0.2.0-SNAPSHOT`

`[WARNING] 'build.plugins.plugin.version' for net.alchim31.maven:scala-maven-plug                                                               in is missing. @ com.criteo.babar:babar-processor:[unknown-version], D:\me\t                                                                ools\babar-master\babar-processor\pom.xml, line 96, column 21`

In order to correct this problem I had to add the version of the plugin in babar-processor/pom.xml:
`                 <groupId>net.alchim31.maven</groupId>`
  `<artifactId>scala-maven-plugin</artifactId>`
              **_`<version>3.4.2</version>`_**

**Comment by BenoitHanotte** [comment]
Hello @andres-lago, Thanks for the feedback, I added the version (albeit a slightly older one to support maven < 3.5.1) to the pom :)
