### ISSUE TITLE
Character / is not accepted for directory name by agent

### ISSUE THREAD

**Issue by andres-lago** [criteo/babar#18]
Sometimes you can need to specify to babar-agent a directory to save the `babar.log` file. If the directory contains the symbol "/", the agent crashes. Example:

`-javaagent:./babar-agent-0.2.0-SNAPSHOT.jar=`**dir=/tmp**`,StackTraceProfiler[profilingMs=60000,reportingMs=60000],JVMProfiler[profilingMs=60000,reservedMB=10376],ProcFSProfiler[profilingMs=60000]"`

The correction is quite simple, you must modify ligne 45 of `com/criteo/babar/agent/config/AgentConfig.java` :

- before:
`static String kv = "([a-zA-Z0-9_\\-\\.]+)=([a-zA-Z0-9:_\\-\\.]+)";`

- after:
  `static String kv = "([a-zA-Z0-9_\\-\\.]+)=([a-zA-Z0-9:_\\-\\./]+)";`

and rebuild babar-agent.

**Comment by BenoitHanotte** [comment]
Hello @andres-lago, thanks a lot for reporting the issue! I fixed it with PR #19 that was just merged :)
