### ISSUE TITLE
Open Source License?

### ISSUE THREAD

**Issue by jimdowling** [criteo/babar#4]
Nice library :)
Should there be an open-source license for it? If yes, could you add it to the project?

**Comment by BenoitHanotte** [comment]
Hello jimdowling! 
Yes, the licence for Criteo's open source software is Apache 2.0, I will update the project in the next couple days to add it. Thanks!

**Comment by BenoitHanotte** [comment]
I am closing this issue as I just added the Apache 2.0 licence file, thanks for reporting!
