### ISSUE TITLE
No jar manifest

### ISSUE THREAD

**Issue by lucienfregosi** [criteo/babar#5]
Hi,

During a spark job execution with the babar-agent jar i got this error message : "error opening zip file or jar, manifest missing, /path/to/babar-agent-1.0-SNAPSHOT.jar"

I built the jar with the command "mvn package" and I got the same error messages with differents spark jobs in multiple edge nodes.

This is the complete error stacktrace : 
![bug](https://user-images.githubusercontent.com/7312730/37413399-4448ad44-27a7-11e8-971a-805a4516648f.png)

And the spark submit arguments I used (I simply add the --files and -- conf related to babar agent to my previous spark submit)

![commandline](https://user-images.githubusercontent.com/7312730/37413449-635ca820-27a7-11e8-982b-8e4e8e299f7c.png)

Thanks for your help and sorry by advance if I missed something

**Comment by BenoitHanotte** [comment]
Hello lucienfregosi, thanks for reporting the issue!
I just tried compiling, deploying and running with Spark and have not been able to reproduce the issue. 
Could you please check that the manifest file is correctly writteny in the jar? You can use the following command line:
```
unzip -c babar-agent/target/babar-agent-1.0-SNAPSHOT.jar META-INF/MANIFEST.MF
```
it should display the following manifest:
```
Manifest-Version: 1.0
Premain-Class: com.criteo.babar.agent.Agent
Archiver-Version: Plexus Archiver
Built-By: benoit
Created-By: Apache Maven 3.3.9
Build-Jdk: 1.8.0_111
```
In this file you can see that the `Premain-Class` is set, and this is the class that `-javaagent` should be looking for.

The command I ran is 
```
$SPARK_HOME/bin/spark-submit \
    --master yarn \
    --deploy-mode cluster \
    --class com.criteo.hadoop.examples.MySparkJob \
    --files /home/b.hanotte/babar-agent-1.0-SNAPSHOT.jar \
    --conf spark.executor.extraJavaOptions="-javaagent:./babar-agent-1.0-SNAPSHOT.jar=StackTraceProfiler[profilingMs=100,reportingMs=60000],MemoryProfiler[profilingMs=5000,reservedMB=7175],CPUTimeProfiler[profilingMs=5000]" \
    --driver-memory 5g \
    --executor-memory 4g \
    --conf spark.yarn.user.classpath.first=true \
    --conf spark.yarn.jars="$BASEDIR/../lib/criteo-hadoop-examples.jar" \
    "$BASEDIR/../lib/criteo-hadoop-examples.jar" 
```

**Comment by lucienfregosi** [comment]
Hello,

Thanks for your response.

I found my mistake it was totally my fault ;-)

In the "--conf" section instead of doing 

`-javaagent:./babar-agent-1.0-SNAPSHOT.jar`

I wrote the entire path like :

`-javaagent:./path/to/babar-agent-1.0-SNAPSHOT.jar`

Now it works like a charm :)

Thanks again
